Ouranosinc/Magpie

.gitignore, AUTHORS.rst, Makefile, magpie/magpie.py, magpie/management/service/resource.py, magpie/models.py, magpie/services.py, magpie/ui/home/static/style.css, magpie/ui/home/templates/home.mako, magpie/ui/login/templates/login.mako, magpie/ui/management/templates/add_resource.mako, magpie/ui/management/templates/add_service.mako, magpie/ui/management/templates/add_user.mako, magpie/ui/management/templates/edit_service.mako, magpie/ui/management/templates/view_groups.mako, magpie/ui/management/templates/view_services.mako, magpie/ui/management/templates/view_users.mako, magpie/ui/management/views.py
- replaces text input by combobox for services' resources according to their respectively allowed resources (ie: only `file`/`directory` selectable within thredds, only `workspace` for WMS)
- removes possibility to add children resources in treeview for `file`
- replace radio buttons in pages `add_user`, `add_service` and `login` by combobox control
- make input forms with comboboxes of same size as input text
- change buttons side-by-side for `view_users`, `view_groups` and `view_services`
- make red button for `delete` operations
- make disabled grey button for not permitted operations according to context (`add_child` / `delete`)
- dynamically change home page buttons position according to available screen width
- made code cleanup according to multiple found deprecation warnings  
- …
=> PAV-415 Improve Magpie UI

magpie/__init__.py, magpie/login/login.py, magpie/magpie.ini, magpie/management/service/service.py, magpie/management/user/user.py, magpie/models.py, magpie/owsrequest.py, magpie/services.py, magpie/ui/home/static/style.css, magpie/ui/management/templates/edit_service.mako, magpie/ui/management/templates/view_groups.mako, magpie/ui/management/templates/view_services.mako, magpie/ui/management/templates/view_users.mako, magpie/ui/management/views.py, register_default_group.py
- add service name/url edition support within `edit_service` page
- add danger confirmation message step for delete service both on `edit_service` and  `view_services` pages
- add `PUT` function to Magpie Rest API to allow modification of a service URL
- suppress some `SAWarning` caused by raw strings passed instead of unicode
- refactor some CSS styles and display of tree items
- add utility CSS styles (banners, info/alert, button styles)
=> PAV-424 - Customize edition of Services + Confirmation Delete

magpie/models.py, magpie/services.py
Enregistrer/Tester les services Pavics sous Twitcher
- ajoute le support de thredds via le ows/proxy
- ajoute la gestion de permission pour visualiser catalog 
- uniformise les classes avec méthodes identiques
- corrige l'obtention de l'URL de la resource exacte au lieu de oneOf
=> PAV438 Thredds Twitcher

magpie/services.py
Manage catalog access with permissions from equivalent urls:
`https://<bird>.crim.ca/ows/proxy/thredds/birdhouse/dummy_files/catalog.html`
`https://<bird>.crim.ca/ows/proxy/thredds/catalog/birdhouse/dummy_files/catalog.html`
1st was failing if `thredds` permission was removed even if every sub-resource permission were allowed
=> different 'catalog' access with valid perms

magpie/management/group/group.py
caused a crash if user / group didn't have any permission on a specific service / resource when requested via `{bird}/magpie/groups/anonymous/services/ncWMS2/permissions`
```
{
"type": "application/json",
"code": 500,
"call": {
"content": "{u'group': {u'users': [<User: anonymous>], u'group_id': 124, u'description': 'None', u'member_count': 0, u'group_name': 'anonymous'}, u'service': {u'service_type': 'wps', u'service_name': 'lb_malleefowl', u'service_url': 'http://colibri.crim.ca:58091/wps', u'permission_names': [], u'resource_id': 1}}",
"exception": "IndexError('list index out of range',)"
},
"detail": "Failed to extract permissions names from group-service"
}
```
```
{
"permission_names": [],
"code": 200,
"type": "application/json",
"detail": "Get group service permissions successful"
} …
```
=> avoid index error if no svc perm for user

magpie/__meta__.py, magpie/alembic/versions/a395ef9d3fe6_reference_root_service.py, magpie/api_except.py, magpie/api_requests.py, magpie/magpie.py, magpie/management/group/group_utils.py, magpie/management/group/group_views.py, magpie/management/resource/resource_formats.py, magpie/management/resource/resource_utils.py, magpie/management/resource/resource_views.py, magpie/management/service/service_formats.py, magpie/management/service/service_utils.py, magpie/management/service/service_views.py, magpie/management/user/user_utils.py, magpie/management/user/user_views.py, magpie/models.py, magpie/register.py, magpie/services.py, magpie/ui/management/views.py
- resources and services now display all **applicable**/**permitted** `permission_names` according to service-specific sub-resources permissions
- user and group resources/services still display only **applied** permissions (ie: same ones as ticked in UI)
- added more checks to restrict creation of unsupported resources under a given service
- added more checks to restrict assignation of unsupported permissions under a specific *service-typed* resource
- db migration for new `root_service_id` stored under every sub-resource
* links are created for existing resources
* created resources will be updated automatically with proper link to service
- magpie `0.5.1`
addresses issue #40 
- adjusted error message returned when user has insufficient permissions to execute a call, now 401 is …
=> Permissions refactoring for Service-typed Resources

magpie/management/group/group_formats.py, magpie/management/group/group_utils.py, magpie/management/group/group_views.py, magpie/management/service/service_utils.py
- fixes the recent issue found by @Renaud009 (https://crim-ca.slack.com/archives/C0Q42FF5F/p1528984613000111)
- add group service created/delete better checks to fix id access
- verify for conflicts during perm creation or not found on delete
- add more details about conflict/notfound parameters
=> resolve 500 on group resource permission delete

docs/magpie-rest-api.yaml, magpie/login/__init__.py, magpie/login/login.py, magpie/magpie.ini, magpie/ui/login/templates/login.mako, magpie/ui/login/views.py
address issue #60 
- no more signin internal/external from UI, all under API
- same `/signin` route for internal/external API
- `signin_internal` is auto-managed by ziggurat for login
- `signin_external` uses the authomatic login, but none really works...
- invalid credentials banner instead of specific info about login failure (issue #59)
- `/signin` (provider_name='ziggurat') => `/signin_internal`
- `/signin` (provider_name=*external provider*) => `/signin_external` => `/providers/{provider}/signin`
- preserve/remove the additional `/providers/{provider}/signin` ? (do everything in `/signin_external`)
- add verification & validation of *token* (?) with external providers
- UI login from a central location (pavics-frontend) ?
`/signin` could maybe be used to first (always) attempt login …
=> Issue 60 signin routes

magpie/alembic/env.py, magpie/alembic/versions/2a6c63397399_separate_personal_standard_groups.py, magpie/alembic/versions/438c27ec1c9_normalize_constraint_and_key_names.py, magpie/alembic/versions/c352a98d570e_project_api_route_resource.py, magpie/models.py, magpie/services.py
- service `project-api` route permission validation
- service `geoserver-api` route permission validation
`https://colibri.crim.ca/twitcher/ows/proxy/project-api/api/Projects`
(aka `https://colibri.crim.ca/project-api/api/Projects`)
`https://colibri.crim.ca/twitcher/ows/proxy/geoserver-api/**`
(aka `https://colibri.crim.ca/geoserver/rest/**`)
- PR Ouranosinc/PAVICS#88 (providers)
- PR Ouranosinc/PAVICS#91 (geoserver security)
- PR Ouranosinc/Magpie#64 (signin)
- PR Ouranosinc/Magpie#67 (API + unittests)
=> Service API permissions

HISTORY.rst, magpie/__meta__.py, magpie/api/management/resource/resource_formats.py, magpie/api/management/resource/resource_utils.py, magpie/models.py, magpie/services.py, magpie/ui/management/templates/edit_service.mako, magpie/ui/management/views.py, providers.cfg
- `ServiceAccess` with single permission `access` to control root path URL
(sub routes under service are all evaluated only based on the root service user access)
- service new parameter `child_resource_allowed ` to block sub-resource creation under service
=> service 'access'

magpie/api/api_rest_schemas.py, magpie/api/management/user/user_views.py, magpie/ui/management/views.py, providers.cfg, tests/interfaces.py
There was a bug in the UI and api when trying to add a user to a group in both the "edit group" view and the "edit user" view.
From the UI, the POST route was: `/users/{user_name}/groups/{group_name}`
I changed it to: `/users/{user_name}/groups` with the group_name in the post data
Also, I had to change the view of the `/users/{user_name}/groups` because it was expecting a group_name in the `matchdict`
=> Fix assigning a user to a group in api and ui

magpie/adapter/__init__.py, magpie/adapter/magpieprocess.py, magpie/adapter/magpieservice.py, magpie/api/api_rest_schemas.py, magpie/api/management/user/user_views.py, magpie/definitions/pyramid_definitions.py, magpie/definitions/twitcher_definitions.py, magpie/magpiectl.py, magpie/register.py, requirements.txt
* adds process store adapter for OGC project
* includes various import/setup fixes
* depends on #104, #107, #109,  #110 (mega merge)
=> Magpie adapter process visibility

magpie/__meta__.py, magpie/api/api_rest_schemas.py, magpie/api/management/group/group_utils.py, magpie/api/management/group/group_views.py, magpie/api/management/resource/resource_views.py, magpie/api/management/service/service_formats.py, magpie/api/management/service/service_views.py, magpie/api/management/user/user_utils.py, magpie/api/management/user/user_views.py, tests/interfaces.py
resolves #108 
Hide value `service_url` under routes `/groups/...` and `/users/...` (especially for `/users/current/...` with public access) so that service unprotected url is not available.
Value `public_url` (proxy) is still returned (the one to be used by users).
Only admins can access `service_url` under `/services` routes.
=> Hide private url

magpie/__meta__.py, magpie/adapter/__init__.py, magpie/adapter/magpieowssecurity.py, magpie/adapter/magpieservice.py, magpie/adapter/utils.py, magpie/api/api_rest_schemas.py, magpie/api/login/login.py, magpie/api/management/group/group_utils.py, magpie/api/management/group/group_views.py, magpie/api/management/resource/resource_formats.py, magpie/api/management/resource/resource_utils.py, magpie/api/management/service/service_formats.py, magpie/api/management/service/service_views.py, magpie/api/management/user/user_utils.py, magpie/api/management/user/user_views.py, magpie/db.py, magpie/definitions/pyramid_definitions.py, magpie/helpers/register_default_users.py, magpie/models.py, magpie/owsrequest.py, magpie/register.py, magpie/services.py, magpie/ui/management/views.py, requirements.txt, tests/interfaces.py, tests/test_magpie_api.py, tests/utils.py
- fixes multiple broken unittests
- move to ziggurat 0.8.1, which uses Service classes for db queries
- document deprecation in swagger to alert users
- adjust magpie adapter using admin query for valid operations by non-admin users
- magpie version 0.7.3
=> Fix tests + Upgrade ziggurat

magpie/__meta__.py, magpie/adapter/magpieprocess.py, magpie/definitions/pyramid_definitions.py
http://ci.corpo.crim.ca:8081/job/OGC_Twitcher_EMS_end2end/117 (Twitcher ogc-0.4.x)
=> update adapter to match twitcher-ogc-0.4.x

magpie/adapter/magpieservice.py
See issue #141 for diagnostic and tests performed on this PR.
=> adapter: fix missing support for self-signed SSL certificate in MagpieServiceStore.list_services() (issue #141)

magpie/magpie.ini
This prints the gunicorn access logs to stdout.
I don't know what you think, but I think this helps debugging...
=> Gunicorn access logs

Dockerfile, magpie/api/management/user/user_utils.py, magpie/api/management/user/user_views.py, magpie/common.py, requirements-py2.txt
CHANGE:
- in the Dockerfile, don't reinstall dependencies when there is only a code change
FIX:
- futures is required for gunicorn threads in python 2.7
- add configparser for python 2.7
- change MAGPIE_DIR from ARG to ENV in Dockerfile
- create_user_resource_permission takes a models.User, not a user id
=> Docker build

magpie/db.py
- Leave pool_size and max_overflow to their default values (5 and 10)
I think that we should not enforce a value of 20 for the connection pool size. The user can now overwrite this setting in the config. 
- Use pool_pre_ping when not set to False in config.
The main problem I encountered was that when the database restarts, connections in the pool are no longer valid. This means that a 500 error will happen when the next query is attempted.
From sqlalchemy docs:
> Pessimistic testing of connections upon checkout is achievable by using the Pool.pre_ping argument, available from create_engine() via the create_engine.pool_pre_ping argument:
> engine = create_engine("mysql+pymysql://user:pw@host/db", pool_pre_ping=True)
> The “pre ping” feature will normally emit SQL equivalent to “SELECT 1” …
=> Change sqlalchemy engine creation default values

HISTORY.rst, magpie/db.py
I found this setting which seems to help a bit.
I am able to add much more users, as the pool is x times the number of workers.
Still, it's more of a patch than anything else.
We should look into avoiding the iterative calls of following function, ran on every create-user submission.
https://github.com/Ouranosinc/Magpie/blob/8fccad35ca3c8b078ae44502d3519b10cfc3801e/magpie/ui/management/views.py#L66-L76
Maybe we could add `GET /users?detail=true`, which would return a list of user-params instead of the flat user-name string list.
@dbyrns What do you think?
=> tmp fix using pool_threadlocal

HISTORY.rst, magpie/api/login/login.py, magpie/db.py, magpie/ui/utils.py
I could reproduce the connection pool issues we were having, and this should fix it. I think multiple threads were getting the same session from the factory, and the sessions were then probably not closed properly.
Also, remove pool_threadlocal which is equivalent to use_threadlocal, which is deprecated.
Explanation here: https://docs.sqlalchemy.org/en/13/orm/contextual.html#thread-local-scope
=> set `use_tweens` to True when using the `invoke_subrequest` pyramid method

magpie/ui/management/templates/edit_group.mako, magpie/ui/management/templates/edit_service.mako, magpie/ui/management/templates/edit_user.mako
Fixed issue where pressing return when editing user password deletes the user completely
Fixed similar issue found on the Groups and Services pages
Fixes #209
=> Issue #209

HISTORY.rst, magpie/ui/management/views.py
=> Fix 500 error when deleting a service resource from the ui

HISTORY.rst, magpie/adapter/__init__.py, magpie/adapter/magpieservice.py
MagpieAdapter can be a singleton, since it doesn't share any state between calls except for the global settings, which aren't modified unless the app is restarted (same for MagpieServiceStore and MagpieOWSSecurity).
The adapter is a class, but behaves more like a module, so to use a singleton is a correct use case here.
Also, when calling `MagpieServiceStore.fetch_by_name`, we don't have to list all services.
=> Magpie adapter singleton

HISTORY.rst, config/magpie.ini, docs/index.rst, docs/performance.rst, magpie/__init__.py, magpie/adapter/__init__.py, magpie/app.py, magpie/models.py, magpie/services.py, requirements.txt
I only tested this with the `ServiceAPI` service type. 
Basically, the permissions are cached for a specific service and user. When there are a lot of concurrent requests, adding a cache with a small expiration time of 5 seconds can make a big difference (2-3 times more requests handled per second).
@fmigneault I don't think so, but look if I didn't miss anything regarding permissions that caching could interfere with...
=> Use pyramid-beaker to cache acl permissions for a specific service and user name

HISTORY.rst, magpie/alembic/versions/c352a98d570e_project_api_route_resource.py
We can't query using models.Resource.resource_type because it's a declared_attr in sqlalchemy. 
In general, migrations that don't depend on the sqlalchemy models will be more stable as the models get modified.
=> Fix migration: don't use the orm

HISTORY.rst, magpie/db.py
Fix for warning: "Textual SQL expression 'alembic_version' should be explicitly
declared as text('alembic_version')"
=> Fix #165 (database version)

HISTORY.rst, magpie/alembic/versions/73b872478d87_add_resource_label.py, magpie/alembic/versions/a395ef9d3fe6_reference_root_service.py
Fix for https://github.com/Ouranosinc/PAVICS/pull/149
The `get_resource_root_service` function is outside of the migration folder. Adding a column to the resource table at a later time means that the migration will try to use this non existing column during the migration when running `get_resource_root_service`.
=> don't use get_resource_root_service in migrations

.dockerignore, CONFIGURATION.rst, CONTRIBUTING.rst, HISTORY.rst, README.rst, config/permissions.cfg, config/providers.cfg, docs/conf.py, docs/configuration.rst, docs/index.rst, docs/installation.rst, docs/usage.rst, magpie/adapter/__init__.py, magpie/api/login/esgfopenid.py, magpie/constants.py, magpie/helpers/sync_services.py, magpie/register.py, magpie/security.py, magpie/utils.py, tests/test_register.py
Adding multiple reviewers to spread the news about added info.
- Adds multiple documentation details about magpie's long list of setup configurations variables.
- Adds support of *multi*-cfg file loading for providers and permissions (in order to support docker-compose configs loaded from many places, such as `config` and `private-config`.
- Improve the generation and rendering of docs.
Fix #173, #180
=> config updates

Dockerfile, requirements.txt
Tested locally, there should be a 1.7.2 release, because gunicorn 20.0.0 breaks magpie 1.7.1
=> pin gunicorn==19.9.0 and wait for patch for 20.0.0

HISTORY.rst, config/magpie.ini, docs/configuration.rst, magpie/app.py, magpie/constants.py, magpie/db.py, magpie/helpers/run_db_migration.py, magpie/register.py
Before this fix, the pasted ini file would define most settings, but ini file employed by db migration would use the default `./config/magpie.ini` path.
We allow also json/yaml file extensions as these formats where already supported for permissions.cfg or providers.cfg, but not explicitly looked for when specifying a directory path to load many files.
- employ gunicorn paste ini file for db migration
- yml/json configs extensions support
=> config improvements

Dockerfile, Makefile, requirements-sys.txt, requirements.txt
pin 'zope.interface>=4.7.0' minimal version (via zopefoundation/zope.interface#30) to fix missing 'Features' feature officially removed (via pypa/setuptools#65) and pin setuptools<46.0.0
references https://github.com/zopefoundation/zope.interface/issues/184
=> pin setuptools version breaking build/install 

magpie/api/generic.py
allow more accept header content-type if ui/static route is requested for app mounted behind proxy with additional prefix than just /magpie
=> accept header checks

.github/workflows/secret-scan.yml, docs/conf.py, docs/configuration.rst, magpie/__init__.py
* avoid import of pyramid in magpie __init__ which break RTD docs build
* remove trufflehog - use only gitleaks
=> doc rst adjustments + github actions

.travis.yml, HISTORY.rst, Makefile, docs/conf.py, hooks/post_push
Since https://github.com/Ouranosinc/Magpie/commit/1c0a1566f94a92e2781a19f5a41d8fedb49e4568, (ie magpie `1.7.4`), any master branch build of the docker image did not create the corresponding sync twitcher image because `MAGPIE_VERSION` -> `APP_VERSION` was not reflected in build hook.
last build of `pavics/twitcher:magpie-latest` ~6 months ago: 
https://hub.docker.com/layers/pavics/twitcher/magpie-latest/images/sha256-9061cff0a712da5570a048a5dbf7429c413a1c61f26026b70a2d52da2a698a44?context=explore
Explicitly tagged versions are not affected as they used the real value of the makefile.
=> fix docker-build-hook for latest twitcher with master/latest magpie

CHANGES.rst, magpie/ui/home/static/style.css, magpie/ui/management/templates/edit_user.mako
Minor UI fix. 
Before / after :
=> fix visual alignment of perm inherited notices

CHANGES.rst, Makefile, docs/permissions.rst, docs/services.rst, magpie/security.py, magpie/ui/home/static/style.css, magpie/ui/management/templates/edit_group.mako, magpie/ui/management/templates/edit_service.mako, magpie/ui/management/templates/edit_user.mako, magpie/ui/management/templates/view_services.mako, magpie/ui/management/views.py, magpie/ui/user/templates/edit_current_user.mako, magpie/ui/utils.py, setup.cfg, tests/runner.py, tests/test_security.py, tests/test_services.py, tests/utils.py
- fix UI error pre-validation of user fields (#369, #370)
- adjust rendered UI error in case of non-HTTP related error
- adjust HTML/CSS mismatches between various forms that were intended to be of 'similar' display format
Example below of displayed contextual error after [password 'Edit', set invalid value, 'Save' button] sequence
=> Fix UI user edit fields error message

CHANGES.rst, Makefile, docs/configuration.rst, docs/services.rst, magpie/adapter/__init__.py, magpie/adapter/magpieowssecurity.py, magpie/adapter/magpieservice.py, magpie/alembic/versions/2020-11-20_cfe64807c143_add_service_custom_configuration_field.py, magpie/api/__init__.py, magpie/api/management/service/service_formats.py, magpie/api/management/service/service_utils.py, magpie/api/management/service/service_views.py, magpie/api/schemas.py, magpie/app.py, magpie/constants.py, magpie/db.py, magpie/models.py, magpie/register.py, magpie/services.py, magpie/typedefs.py, magpie/ui/home/static/style.css, magpie/ui/home/static/themes/blue.css, magpie/ui/home/static/themes/green.css, magpie/ui/management/templates/edit_service.mako, magpie/ui/management/templates/tree_scripts.mako, magpie/ui/management/templates/view_services.mako, magpie/ui/management/views.py, magpie/utils.py, tests/test_services.py, tests/utils.py
@tlvu @dbyrns 
Regarding comments in https://github.com/bird-house/birdhouse-deploy/pull/102
This PR adds the JSON config from `providers.cfg` / `config.yml` and stores it directly into postgres. 
This allows Twitcher to retrieve the same config later on.
Below samples use this config: 
``` yaml
providers:
TestThredds:
url: http://${HOSTNAME}:8000/thredds
type: thredds
configuration:
file_patterns:
- ".+\\.nc"
metadata_type:
prefixes:
- null  # note: special YAML value evaluated as `no-prefix`, use quotes if literal value is needed
- "\\w+\\.gif"  # favicon, threddsIcon, etc.
- "\\w+\\.txt"  # licence
- "\\w+\\.css"  # tds.css
- "catalog\\.\\w+"  # note: special case for `THREDDS` top-level directory (root) accessed for `BROWSE`
- catalog
- ncml
data_type:
prefixes:
- fileServer
- dodsC
- …
```
=> Store custom config JSON in db 

CHANGES.rst, Dockerfile.adapter
include fix of incorrect `python3-dev` from Twitcher's docker employed for the adapter image
https://github.com/bird-house/twitcher/pull/99
=> bump twitcher 0.5.4 -> 0.5.5

magpie/api/management/register/register_utils.py, magpie/api/management/user/user_utils.py, magpie/api/management/user/user_views.py, magpie/api/schemas.py, magpie/api/webhooks.py, magpie/app.py, magpie/models.py, tests/test_webhooks.py, tests/utils.py
I completed the missing part for the tmp_url with Francis' new code, and completed the FailingWebhook test case.
Note that I couldn't call the tmp_url directly from the webhook app, or at least, it would have been complicated, so instead, I just save the tmp_url value in the webhook_app, and retrieve it from the test case where I have easy access to the local Magpie app to call the tmp_url. I think this is fine as it still tests the tmp_url feature and tests the validity of the TemporaryToken id.
Let me know what you guys think!
=> Finish the missing tmp_url part for the webhooks

Makefile
result of `make` (to display targets) following update
```
=== magpie help ===
Please use 'make <target>' where <target> is one of:
help                     print this help message (default)
version                  display current version
info                     display make information
clean                    alias for 'clean-all' target
clean-all                remove all artifacts
clean-build              remove build artifacts
clean-docs               remove doc artifacts
clean-pyc                remove Python file artifacts
clean-test               remove test and coverage artifacts
clean-docker             alias for 'docker-clean' target
migrate                  alias to 'database-migration'
database-migration       run postgres database migration with alembic
database-history …
```
=> add 'only' targets to skip installs as needed

CHANGES.rst, Dockerfile, Makefile, bin/gunicorn, config/magpie.ini, docs/configuration.rst, docs/installation.rst, docs/performance.rst, docs/references.rst, docs/usage.rst, magpie/app.py, requirements-dev.txt, requirements.txt, setup.py
- Update to most recent gunicorn version such that security fixes and performance improvements are integrated (resolve #410)
- General docs updates.
**important** 
needs to be properly updated in daccs/pavics, as the necessary binding changes using `pserve`
config INI with `host = localhost` does not work 
relates to https://github.com/bird-house/birdhouse-deploy/pull/143
=> Gunicorn update

CHANGES.rst, Makefile, config/config.yml, config/permissions.cfg, config/providers.cfg, docs/configuration.rst, magpie/api/schemas.py, magpie/api/webhooks.py, magpie/models.py, magpie/register.py, magpie/services.py, magpie/typedefs.py, setup.cfg, tests/interfaces.py, tests/test_register.py
* Add explicit typing definitions of configuration files and resolved settings to facilitate discovery of invalid
handling of formats or parameters during parsing and startup registration.
* Apply many documentation updates in both configuration sections and the corresponding configuration example headers.
* Fix ``users`` and ``groups`` registration configurations not respecting update method when conflicting
definitions occur. They will respect alphabetical file name order and later ones remain.
* Fix ``users`` and ``groups`` registration configurations not correctly parsed when multiple files where employed (fixes #429).
=> Fix config loading

CHANGES.rst, docs/configuration.rst, magpie/api/webhooks.py, magpie/app.py, magpie/constants.py, tests/test_register.py, tests/test_webhooks.py
Identified while working on #430 
This will be of good interest when integrating with `cowbird`. 
* Add ``MAGPIE_WEBHOOKS_CONFIG_PATH`` configuration setting / environment variable that allows potentially using
multiple configuration files for `Webhooks`. This parameter is notably important for developers that where using the
``MAGPIE_PROVIDERS_CONFIG_PATH`` or ``MAGPIE_PERMISSIONS_CONFIG_PATH`` settings to load multiple files, as they
cannot be combined with single configuration provided by ``MAGPIE_CONFIG_PATH``, which was the only supported way to
provide `Webhooks` definitions.
Other updates are related to above.
=> Webhook config multi

CHANGES.rst, magpie/api/management/user/user_utils.py, magpie/ui/user/views.py
fix resolution of missing MAGPIE_USER_REGISTRATION_ENABLED setting during user email update (fixes #459)
tested manually by removing the setting from config and checking that update worked + warning was printed indicating that default (false) was used because setting was not found.
=> MAGPIE_USER_REGISTRATION_ENABLED default to false when omitted

CHANGES.rst, magpie/api/management/service/service_utils.py, magpie/api/management/service/service_views.py, magpie/api/schemas.py, tests/interfaces.py
* Improve API update operation of ``Service`` for allowed fields in order to accept body containing only the
new value for the custom ``configuration`` without additional parameters. It was not possible to
update ``configuration`` by itself, as ``service_name`` and ``service_url`` were independently validated
for new values beforehand.
* Fix erasure value ``None`` (JSON ``null``) validation when updating ``Service`` field ``configuration`` to
properly distinguish explicitly provided ``None`` against default value when the field is omitted.
* Fix incorrect OpenAPI body schema indicated in response of ``POST /services`` request.
* Updated tests for new use cases.
=> fix and improve handling of parameter update of service API request

CHANGES.rst, Dockerfile.adapter, Makefile, docs/conf.py, magpie/alembic/versions/2021-04-16_dea413e13a8a_pending_users_and_statuses.py, magpie/ui/management/views.py, magpie/ui/user/views.py, requirements-dev.txt, requirements-doc.txt, requirements.txt
When combining Magpie and Twitcher in the docker adapter image, Twitcher's more recent dependencies about `sqlalchmy` (https://github.com/bird-house/twitcher/blob/202377532a921940143af1d360bc0e51d938dad2/requirements.txt), which forces `SQLAlchemy>=1.4` causes a mismatch with expected versions in Mapgie, which where tested with `SQLAlchemy==1.3`. 
More specifically, package `ziggurat_foundations` causes the following error : 
```
>Textual column expression 'depth' should be explicitly declared with text('depth'), or use column('depth') for more specificity
```
when reaching the following code `ziggurat_foundations.models.services.resource_tree_postgres.ResourceTreeServicePostgreSQL.from_parent_deeper`
```python
query = db_session.query(cls.model, "depth", "sorting", "path")
```
Depends on …
=> pin sqlalchemy & related packages to avoid issue in ziggurat_foundations

CHANGES.rst, magpie/adapter/__init__.py, magpie/adapter/magpieowssecurity.py, magpie/api/management/group/group_utils.py, magpie/api/management/resource/resource_utils.py, magpie/api/management/service/service_utils.py, magpie/api/management/user/user_utils.py, magpie/api/notifications.py, magpie/models.py, magpie/permissions.py, magpie/register.py, magpie/services.py
- add more debug logging during effective perm/acl resoluion 
- add session merge/reconnect of `resource` object between service/acl caches
relates to #466
=> Debug Logging and Attempt to resolve caching issues

CHANGES.rst, magpie/api/management/group/group_utils.py, magpie/api/management/group/group_views.py, magpie/api/management/service/service_utils.py, magpie/api/management/service/service_views.py, magpie/api/management/user/user_utils.py, magpie/api/management/user/user_views.py, magpie/api/schemas.py, magpie/permissions.py, magpie/ui/management/templates/tree_scripts.mako, magpie/ui/management/views.py, tests/interfaces.py, tests/utils.py
* Add ``type`` query parameter to multiple requests returning ``Services`` or ``Resources`` regrouped by ``ServiceType``
for a given ``User`` or ``Group`` in order to limit listing in responses and optimise some operations where only a
subset of details are needed.
* Using new ``type`` query to filter ``ServiceType``, improve ``Permissions`` listing in UI pages with faster processing
because ``Services`` that are not required (since they are not currently being displayed by the tab-panel view) can
be skipped entirely, removing the need to compute their underlying ``Resource`` and ``Permissions`` tree hierarchy.
- fixes #463
=> add type query parameter to filter requested services/resource tree

CHANGES.rst, magpie/services.py, tests/test_services.py
Using test results of https://github.com/bird-house/birdhouse-deploy/pull/197#issuecomment-978164867
And the extended stress-test logs in daccs-jenkins.crim.ca/job/PAVICS-e2e-workflow-tests/job/master/663
We can see that previous places where most of the time that ``DetachedInstanceError`` and ``NoTransaction`` were raised are gone. 
Only two case where raised within the thousands of requests.
Attempt to fix them with similar operation reconnecting the session or reattaching the object to it. 
Added a minimal test to early detect such situations in the future if a new step is added to the code, but those errors are really hard to evaluate more than this.
=> Fix reconnect user / session

.github/.gitleaks.toml, CHANGES.rst, Dockerfile.adapter, config/magpie.ini, magpie/__init__.py, magpie/adapter/__init__.py, magpie/adapter/magpieowssecurity.py, magpie/api/generic.py, magpie/app.py, magpie/cli/batch_update_users.py, magpie/db.py, magpie/security.py, magpie/services.py, magpie/utils.py, requirements-dev.txt, requirements.txt, tests/utils.py
Even with previous patches in `3.18.x` releases, some cases still seem to generate sporadic `NoTransaction` errors. 
- In order to (hopefully) fix this once and for all, add a retry operation specifically for the corresponding errors happening when desync of cached vs live db session are used.
- Combine the transaction/database/user configuration attached to the request on both `Magpie` itself and the `MagpieAdapter`, into a reusable setup function. 
- Clean/refactor the config setup using above function and centralize them into application main.
- Attempt session reconnect in a few more places that where highlighted in https://github.com/bird-house/birdhouse-deploy/pull/197#issuecomment-980431919
- Integrate fixes from https://github.com/bird-house/twitcher/pull/111
=> Retry session tm failure

CHANGES.rst, magpie/adapter/magpieowssecurity.py, requirements.txt
- use uuid/request mapping to persist distinct handles until cached service completely finishes computing the object 
- relates to #490
- relates to https://github.com/bird-house/birdhouse-deploy/pull/224#issuecomment-985668339)
- use feature https://github.com/bbangert/beaker/pull/221
- potential fix of https://github.com/Ouranosinc/Magpie/issues/492
=> fix failing cached service creation

CHANGES.rst, magpie/ui/home/static/style.css, magpie/ui/home/templates/restore_scroll.js, magpie/ui/home/templates/template.mako, magpie/ui/management/templates/add_service.mako, magpie/ui/management/templates/edit_service.mako, magpie/ui/management/templates/tree_scripts.mako
* Add auto-restore of previous scroll position in UI page following submitted form.
* Add UI tooltip `Resource` ID to elements rendered in the ``Service`` and ``Permission`` hierarchy trees
(relates to #335).
* Fix UI alignment of permission titles with their corresponding permission selectors
(relates to #498).
=> fix alignment of permission title/combobox

CHANGES.rst, Makefile, magpie/services.py, magpie/ui/home/static/style.css, magpie/ui/management/templates/edit_service.mako, magpie/ui/management/templates/tree_scripts.js, magpie/ui/management/templates/tree_scripts.mako, magpie/ui/management/views.py, tests/test_magpie_ui.py, tests/utils.py
When permissions cannot fit in view, an horizontal scrollbar appears under the permission titles. 
Scrolling it moves all the selector boxes across all lines in the tree view accordingly.
* Add UI horizontal multi-scroll (all tree lines simultaneously) of ``Permission`` selectors when there are more that
can fit naturally within the tab view for a given ``Service`` type  (relates to #498).
* Widen permission "columns" for more permission titles to fit.
The permission titles can still auto-scroll as well in cases were the permission name is just unreasonably long.
The chosen dimension is the best trade-off of showing as must titles completely vs making the boxes too wide, needing extra scrolling to display all of them.
* minor fixes related to linting
=> fix display of permission comboboxes with scrollable columns across lines

CHANGES.rst, config/permissions.cfg, magpie/api/management/resource/__init__.py, magpie/api/management/resource/resource_views.py, magpie/api/schemas.py, magpie/register.py, tests/interfaces.py, tests/test_register.py
Content of this PR :
* Add ``PATCH /permissions`` endpoint that updates permissions and creates related resources if necessary.
* ``permissions.cfg`` now supports a new format for the ``type`` parameter, using multiple types separated
by a slash character, matching each type with each resource found in the ``resource`` parameter.
=> Permissions patch

CHANGES.rst, docs/configuration.rst, docs/glossary.rst, magpie/adapter/__init__.py, magpie/api/management/resource/resource_utils.py, magpie/services.py, magpie/typedefs.py, tests/hooks/request_hooks.py
Add ``context`` parameter available for `Service Hook` functions, offering more handlers to obtain references to
the adapter, the request's `Service` implementation, and the corresponding database `Resource`. This can be used,
amongst other things, to perform advanced operations such as validating other `Resource` and `Permission` conditions
to modify the handled ``request`` or ``response`` by the hook.
When attempting to implement [DAC-178 *6.2.2 - Filter processes based on permissions*](https://crim-ca.atlassian.net/browse/DAC-178), it became quite obvious that the parameters offered by hooks were not sufficient. For filtering items returned by `/processes` for example, a check of all items in that response must be done. With the previous parameters, this involved recomputing many …
=> adapter request/response hook `context` parameter

.github/workflows/secret-scan.yml, .github/workflows/tests.yml, .pylintrc, CHANGES.rst, Makefile, magpie/alembic/script.py.mako, magpie/alembic/versions/2022-09-01_5e5acc33adce_case_insensitive_email_constraint.py, magpie/api/management/user/user_utils.py, magpie/api/schemas.py, magpie/models.py, magpie/ui/home/static/style.css, magpie/ui/management/templates/edit_user.mako, magpie/ui/management/templates/view_pending_user.mako, magpie/ui/management/templates/view_users.mako, magpie/ui/management/views.py, magpie/ui/user/templates/edit_current_user.mako, magpie/ui/utils.py, requirements-dev.txt, requirements-doc.txt, tests/interfaces.py, tests/utils.py
* Add database unique index to ensure case-insensitive ``User`` email cannot be stored.
* Display ``User`` email field in UI page providing the list of registered and pending users.
* Add ``mailto:`` link for all ``User`` email fields displayed in UI.
* Fix conflicting ``User`` email not properly reported in UI with an appropriate message in creation page.
The ``User`` name was instead reported as the conflicting property, although it was not the problematic field 
(resolves #521).
If any ``User`` entries with duplicate case-insensitive emails are present in the database, the application will fail when performing the database migration. Resolve those cases manually before starting `Magpie`.
=> fix email related validation to avoid duplicates

config/config.yml
Fix example config.yml to be valid YAML in case loaded by parser/validator/security checks.
=> fix example config.yml to be valid YAML 

docs/conf.py
Avoid failing checks for external causes.
When performing link-checks in the documentation and code docstrings, any login provider that is down due to maintenance fails the PR and validation pipeline. Use a status endpoint that reports down instances to consider them as unreachable and temporarily ignore them to avoid the "broken" link errors.
=> ignore linkcheck on down login providers when their servers status are down

.github/workflows/tests.yml, CHANGES.rst, README.rst, setup.py
- add Python 3.9, 3.10, 3.11 to test pipeline
- mark Python 3.5, 3.6 as legacy support
- drop Python 2.7 support (officially, but was not working for a while due to recent changes)
=> maintenance update of Python versions

Makefile
Relates to https://github.com/sqlalchemy/sqlalchemy/pull/8563
Flagged issue is not employed. 
It also points to a non-prod ready version of sqlalchemy and a potential major change.
=> ignore safety security warning about sqlalchemy>=2.0.0b1 still in beta

requirements.txt
=> pin `ziggurat_foundations==0.9.1` for latest `sqlalchemy`-related security fixes

CHANGES.rst, magpie/api/management/group/group_utils.py, magpie/api/management/user/user_utils.py, magpie/api/webhooks.py, tests/test_webhooks.py
Add the `service.type` data in the `Webhooks` for a `Permission` change, even if the resource is not a service,
since the root service type is necessary to `Cowbird`.
=> add service type to permission webhooks

.readthedocs.yml, CHANGES.rst, Makefile, config/providers.cfg, docs/conf.py, docs/services.rst, magpie/owsrequest.py, magpie/services.py, magpie/ui/home/static/style.css, magpie/ui/management/templates/edit_group.mako, magpie/ui/management/templates/edit_service.mako, magpie/ui/management/templates/edit_user.mako, magpie/ui/management/templates/view_pending_user.mako, magpie/ui/management/views.py, magpie/ui/user/templates/edit_current_user.mako, magpie/xml_util.py, setup.cfg, tests/interfaces.py, tests/test_adapter.py, tests/test_services.py
* Add support of RESTful API endpoints (i.e.: ``ServiceAPI``) under ``ServiceGeoserver`` using ``Route`` resources
(fixes https://github.com/Ouranosinc/Magpie/issues/584).
Requires the `Service` to be configured either with the default ``configuration``,
or by explicitly setting ``api: true``. When a HTTP request is sent toward a `Service` typed ``ServiceGeoserver``,
any non-`OWS` request (i.e.: `WFS`, `WMS`, `WPS`) will default to the resolution handling of typical ``ServiceAPI``.
This can be used notably to access the ``/web`` and ``/ogc`` endpoints of a `GeoServer` instance.
* Fix `UI` rendering of the `Permission` label list under a `Service` edition page when a large amount of possible
permissions is applicable. This was notably the case of ``ServiceGeoserver`` that combines …
=> support API request paths under GeoServer service

CHANGES.rst, magpie/api/management/resource/resource_views.py, magpie/api/management/service/service_views.py, magpie/api/schemas.py, magpie/typedefs.py, tests/interfaces.py, tests/test_magpie_api.py, tests/utils.py
* Add `API` endpoint ``GET /services/{service_name}/resources/{resource_id}`` similar to
existing endpoint ``GET /resources/{resource_id}`` allowing retrieval of a `Resource` details
with prior validation that it lies under the referenced `Service`
(fixes #347).
* Improve ``JSON`` typing definitions to reduce false-positives linting errors and add missing typing definitions.
=> Add API endpoint ``GET /services/{service_name}/resources/{resource_id}``

CHANGES.rst, magpie/utils.py
* Fix returned headers in ``401 Unauthenticated`` response which did not properly employ ``Authentication-Control``
header to return the ``location-when-unauthenticated`` parameter instead of returning it directly as invalid header.
=> fix returned headers on 401 response

CHANGES.rst, magpie/register.py
relates to https://github.com/bird-house/birdhouse-deploy/pull/348
=> allow service registration forced update of type field

CHANGES.rst, config/magpie.ini, docs/configuration.rst, magpie/api/management/user/user_utils.py, magpie/api/schemas.py, tests/interfaces.py, tests/test_magpie_api.py
Create an additional settings/environment variable `MAGPIE_SUPPLEMENTAL_USERNAME_REGEX` that acts as an additional check for whether a `username` is valid. This creates a further restriction on this value which is useful when there are additional limits on the `username` that should be enforced by `Magpie`.
Resolves #497
=> Add supplemental regex setting to validate username

CHANGES.rst, docs/configuration.rst, magpie/api/exception.py, magpie/api/management/user/user_utils.py, tests/interfaces.py, tests/test_magpie_api.py
Ensures that the settings/environment variable ``MAGPIE_USER_NAME_EXTRA_REGEX`` is case sensitive.
Previously, the check was case insensitive meaning that it could not be used to restrict usernames based on case.
For example, setting this value to `^[a-z]+$` would have permit the username `"someuser"` as well as `"Someuser"`. 
Now, the same regular expression will not match `"Someuser"` since case sensitivity in enforced.
=> allow case sensitive regex matches for the `MAGPIE_USER_NAME_EXTRA_REGEX` setting

CHANGES.rst, magpie/alembic/versions/2023-11-10_91af68bcdc67_case_insensitive_user_name_constraint.py, magpie/api/management/user/user_utils.py, tests/interfaces.py
Ziggurat foundations assumes that a `User` will not have a ``user_name`` that differs from another only in terms of case. The simplest way to enforce this is to ensure that all ``user_name`` values are lowercase. 
Previously, this was not enforced so we could create two `User` which could not be differentiated properly.
This change includes a database migration that will convert all ``user_name`` that contain uppercase characters to lowercase. This may cause a database conflict if there are two ``user_name`` values that differ only in terms of case. For example "Test" and "test". If this occurs, please manually update those ``user_name`` values to no longer conflict and try the migration again.
This also prevents new users from being created that contain whitespace.
Replaces #596 …
=> Ensure that ``user_name`` values for all `User` are lowercase and do not contain whitespace

CHANGES.rst, requirements.txt
The ``cornice`` package dropped support for python 3.5 as of version 6.1.0. Update the requirements file to ensure that a supported version of ``cornice`` is installed for python 3.5.
=> pin cornice version to <6.1 for python 3.5

.github/workflows/tests.yml, CHANGES.rst, magpie/__init__.py, requirements-dev.txt, requirements-doc.txt, requirements-sys.txt, requirements.txt, setup.py
* Add support of Python 3.12.
> [!NOTE]  
> Requires patch of ``authomatic.six.moves`` in ``magpie.__init__.py`` to work around vendor-specific definitions.
Fix inspiration from https://github.com/dpkp/kafka-python/issues/2401#issuecomment-1760208950.
Pending official fix (see https://github.com/authomatic/authomatic/issues/233).
* Drop support of Python 3.5, 3.6 and 3.7. Minimum version is Python 3.8.
* Pin ``gunicorn>=22`` to address CVE-2024-1135.
=> Maintenance update

CHANGES.rst, magpie/cli/batch_update_permissions.py, magpie/constants.py, magpie/register.py, setup.cfg, setup.py, tests/interfaces.py, tests/test_magpie_cli.py, tests/test_register.py, tests/utils.py
- define a CLI operation for batch permission update (fixes #611)
- add tests for #610
=> CLI for permissions batch update

CHANGES.rst, docs/conf.py, magpie/cli/batch_update_permissions.py, magpie/constants.py, magpie/register.py, setup.cfg, setup.py, tests/interfaces.py, tests/test_magpie_cli.py, tests/test_register.py, tests/utils.py
Tested using `magpie.register.magpie_register_permissions_from_config` from a script with a set of *Permission* entries and a remote Magpie instance URL. Updates applied where things broke.
=> fix permissions update from config using requests code path

CHANGES.rst, docs/services.rst, magpie/services.py, tests/test_services.py
Resolves #633 
Also updates a broken docs link (unrelated to this PR but required to make CI tests run)
=> Allow `metadata_type.prefixes` and `data_type.prefixes` in `ServiceTHREDDS` configuration to contain `/` character

CHANGES.rst, Makefile, magpie/api/exception.py, requirements-dev.txt
Depends on https://github.com/PyCQA/doc8/pull/148
Requires eventual release of `doc8>=1.1.2` integrating above fix.
=> fix doc8 config parsing error
