Ouranosinc/Magpie

- magpie/ui/home/static/style.css
- magpie/ui/management/templates/edit_service.mako
- magpie/ui/management/templates/view_services.mako
* change the `✓` and `×` for corresponding buttons in alert message for service deletion
* make input fields for service name & URL auto-adjust its width based on its content
> PAV424 extra tweaks

- magpie/api_except.py
Resets the `RAISE_RECURSIVE_SAFEGUARD_COUNT` global variable when the final HTTP return/raise is reached to avoid gradual accumulation of raises.
Without reset, different error raising requests (without anything to do with each other) would increment the counter seperately, and when it reached 5, the unlucky request at that instant gets a HTTP Internal Server Error instead of expected error handling.
> reset recurse on last raise http

- magpie/ui/home/static/style.css
- magpie/ui/management/templates/edit_service.mako
very simple update to make clickable links from services url
> make services urls as actual links

- magpie/ui/home/static/style.css
fix incorrectly set styles that made weird link behaviour on home buttons
> fix home btn links & colors

- magpie/management/user/user.py
- magpie/ui/management/views.py
fix error found during Magpie 0.2.7 review ([PR#20](https://github.com/Ouranosinc/Magpie/pull/20))
updated on `colibri`
> fix create user from Magpie UI

- magpie/ui/home/templates/template.mako
fix error found during Magpie 0.2.7 review ([PR#20](https://github.com/Ouranosinc/Magpie/pull/20))
> fix administration link to home

- .gitignore
- Dockerfile
- HISTORY.rst
- Makefile
- docs/conf.py
- docs/magpie.esgf.rst
- docs/magpie.home.rst
- docs/magpie.local.rst
- docs/magpie.login.rst
- docs/magpie.management.group.rst
- docs/magpie.management.rst
- docs/magpie.management.service.rst
- docs/magpie.management.user.rst
- docs/magpie.rst
- docs/magpie.ui.home.rst
- docs/magpie.ui.login.rst
- docs/magpie.ui.management.rst
- docs/magpie.ui.rst
- docs/modules.rst
- magpie/__meta__.py
- magpie/api_except.py
- setup.cfg
1. merge to develop [PR#21][pr-21] and [PR#22][pr-22], this will update [PR#20][pr-20]
2. update version to 0.3.0 with this merge to develop, will also update [PR#20][pr-20]
3. merge [PR#20][pr-20] to master
4. push new tag 0.3.0 to new master commit
5. update docker image (if needed? maybe will build automatically with new tag push)
[pr-20]: https://github.com/Ouranosinc/Magpie/pull/20
[pr-21]: https://github.com/Ouranosinc/Magpie/pull/21
[pr-22]: https://github.com/Ouranosinc/Magpie/pull/22
> magpie version++

- magpie/__meta__.py
- magpie/register.py
- magpie/ui/home/static/style.css
- magpie/ui/management/templates/view_services.mako
- magpie/ui/management/views.py
- add button only visible in /magpie/services/wps to push all services
- success/failure of push is displayed by status message
- improve checks of push to properly inform about success/failure
> Push all Services to Phoenix Button + Improve

- magpie/__meta__.py
- magpie/login/login.py
- magpie/ui/login/templates/login.mako
- magpie/ui/login/views.py
> Issue 30 login message failure

- magpie/common.py
- magpie/management/service/service_utils.py
- magpie/register.py
- magpie/services.py
- magpie/ui/management/views.py
- providers.cfg
- register_providers.py
merging in Ouranosinc/Magpie#37 because of pending dependencies
addresses issue #39
> project api service

- HISTORY.rst
- magpie/ui/login/views.py
- actually use the logout API route (forget was duplicated in UI)
- update history
> minor updates

- magpie/__meta__.py
- magpie/management/user/user_views.py
- magpie/ui/login/views.py
- fix not filtered service permissions
- fix logout not working from UI
> Magpie 0.5.2

- docs/magpie-rest-api.yaml
- magpie/management/user/user_utils.py
- magpie/management/user/user_views.py
- some cleanup done to match recent changes
- all errors fixed (the big red popup at start of page)
- added 'current' user routes (separate section)
https://app.swaggerhub.com/apis/CRIM/magpie-rest_api/0.5.x
resolves issue #57
> Update Magpie REST API docs 

- magpie/__meta__.py
- magpie/api_requests.py
- magpie/services.py
- providers.cfg
resolves #50 
addresses #39
references PR #48 
used by [twitcher tag pavics-0.3.4](https://github.com/Ouranosinc/twitcher/tree/pavics-0.3.4)
used by PR Ouranosinc/PAVICS#87
> Support project-api route via Twitcher

- HISTORY.rst
- magpie/ui/management/templates/edit_service.mako
> better display of service permissions

- magpie/api/api_rest_schemas.py
- magpie/api/management/group/group_utils.py
- magpie/api/management/group/group_views.py
- magpie/api/management/resource/resource_utils.py
- magpie/api/management/user/user_utils.py
- magpie/api/management/user/user_views.py
- add group schemas 
- transfer remaining user response schemas
references #68, #85
> API schemas (part 2)

- magpie/adapter/magpieservice.py
When using `MagpieAdapter` configured by twitcher with `MAPGIE_URL=localhost:2001/magpie`, requests call fail with invalid scheme error.
Fix by padding `http://` as required if scheme is not found.
Note, `https` will need to be added explicitly to the config of the bird servers.
> auto-adjust localhost adapter service store URL

- magpie/adapter/magpieprocess.py
required to allow updating visibility value of process + access to quotations route
> fix omitted /quotations resource creation

- magpie/__meta__.py
- magpie/adapter/__init__.py
- magpie/adapter/magpieprocess.py
- magpie/api/api_except.py
- magpie/api/api_rest_schemas.py
- magpie/api/login/login.py
- magpie/api/management/user/user_views.py
- tests/interfaces.py
- avoid update user on invalid paramters
- fix 500 error on MagpieAdapter 'ems' process create/retrieve
- properly filter processes according to user perms + process visibility
> User PUT fixes and tests + Adater fixes

- magpie/__meta__.py
- magpie/adapter/magpieprocess.py
- Adjustments required to match [OGC/testbed14-twitcher PR#44](https://www.crim.ca/stash/projects/OGC/repos/testbed14-twitcher/pull-requests/44)
- magpie v0.7.10
> MagpieAdapter Process visibility updates

- magpie/__meta__.py
- magpie/adapter/magpieprocess.py
override list processes for admin regardless of permissions
> List processes adapter

- magpie/__meta__.py
- magpie/adapter/magpieservice.py
- adjust service adapter to match inputs twitcher ogc-0.4.6
- add super init
- version 0.8.1
> Adapter visibility service

- Dockerfile
- magpie/alembic/env.py
- magpie/db.py
- magpie/helpers/sync_resources.py
- requirements.txt
replaces #143 with rebased changes on top of master
> Docker strip + db migration

- .codacy.yml
- .travis.yml
- Dockerfile
- Makefile
- README.rst
- magpie/api/api_except.py
- magpie/db.py
- magpie/ui/home/static/style.css
- magpie/ui/management/views.py
- requirements-dev.txt
see https://github.com/Ouranosinc/Magpie/tree/codacy to have the updated readme view
will add a second "checker" during PRs that does static analysis of code patterns, security risks and such.
> codacy settings and badge

- HISTORY.rst
- magpie/db.py
- magpie/ui/management/views.py
> Fixes db ui

- HISTORY.rst
- magpie/adapter/__init__.py
- magpie/adapter/magpieowssecurity.py
- magpie/api/requests.py
- magpie/models.py
- magpie/utils.py
to help debugging Twitcher adapter
set/add in `twitcher.ini`
DEBUG **HAS** to be removed after, as this info is very sensible
```
[loggers]
keys = root, twitcher, magpie, sqlalchemy
[logger_magpie]
level = DEBUG
handlers =
qualname = TWITCHER
```
> debug auth user

- HISTORY.rst
- magpie/adapter/__init__.py
- magpie/security.py
includes previous fixes (closes #199)
add `/verify` request
> verify user + debug auth user2

- HISTORY.rst
- magpie/alembic/versions/a395ef9d3fe6_reference_root_service.py
- magpie/alembic/versions/c352a98d570e_project_api_route_resource.py
Fixes the error encountered during migration.
Using the db you provided, I reach the "latest" version and Magpie is booted.
Fix for Ouranosinc/PAVICS#149
> fix migraiton script

- HISTORY.rst
- magpie/api/generic.py
> yet another use case to handle prefix path resources matching magpie

- .pylintrc
- HISTORY.rst
- docs/configuration.rst
- magpie/adapter/__init__.py
- magpie/api/exception.py
- magpie/api/management/group/group_formats.py
- magpie/api/management/group/group_utils.py
- magpie/api/management/resource/resource_utils.py
- magpie/api/management/service/service_formats.py
- magpie/api/management/service/service_utils.py
- magpie/api/management/user/user_utils.py
- magpie/api/requests.py
- magpie/app.py
- magpie/constants.py
- magpie/db.py
- magpie/helpers/register_default_users.py
- magpie/helpers/sync_resources.py
- magpie/helpers/sync_services.py
- magpie/models.py
- magpie/permissions.py
- magpie/register.py
- magpie/security.py
- magpie/services.py
- magpie/ui/management/views.py
- magpie/ui/utils.py
- magpie/utils.py
- tests/interfaces.py
- tests/test_services.py
- tests/test_utils.py
- tests/utils.py
- debug level to log more request details
- handle log level from different settings
> extra request log

- Makefile
fix potential miniconda fetch error due to reference url recently needing follow redirect
> curl conda

- HISTORY.rst
- setup.cfg
old: 
https://github.com/Ouranosinc/Magpie/blob/e7d5fbeb62e197c31b484382fce19bf64d2a2ec2/HISTORY.rst
new:
https://github.com/Ouranosinc/Magpie/blob/b6baa01e66400386d370c8b613ec4374d8e087a5/HISTORY.rst
> update changelog with url references

- CHANGES.rst
- config/config.yml
- magpie/api/schemas.py
- magpie/cli/batch_update_users.py
> employ provided user pwd from config.yml in CLI batch creation

- CHANGES.rst
- docs/services.rst
- magpie/services.py
- tests/test_services.py
replaces #366 using original regex group match syntax (more flexible)
> add catalog.* regex for ServiceTHREDDS using re groups match method

- CHANGES.rst
- config/permissions.cfg
- config/providers.cfg
- docs/configuration.rst
- magpie/register.py
- tests/interfaces.py
- tests/test_register.py
- fix missing execution of register tests 
- fix handling of  JSON/str explicit permission definition from config
> fix permission set from config

- CHANGES.rst
- Dockerfile.adapter
> bump twitcher v0.5.4 (performance fix bird-house/twitcher#98)

- magpie/__meta__.py
- setup.py
Value did not match the actual `LICENSE` file.
> patch incorrect license metadata

- .github/labeler.yml
- Makefile
- docs/conf.py
- requirements-doc.txt
fixes https://github.com/sqlalchemyorg/sphinx-paramlinks/issues/5
> fix doc generation with updated sphinx min version and extensions

- CHANGES.rst
- docs/references.rst
- magpie/api/webhooks.py
- magpie/utils.py
- raise appropriate error message when INI not found instead of IndexError caused by that missing file
- fix minor typos
> improve INI not found error message

- Makefile
- ci/docker-compose.smoke-test.yml
> attempt validate webapp response before test-remote execution

- magpie/adapter/magpieowssecurity.py
- tests/test_adapter.py
- tests/utils.py
> Adapter cache service [test]

- CHANGES.rst
- magpie/api/management/user/user_views.py
- magpie/api/schemas.py
- magpie/typedefs.py
- magpie/ui/management/views.py
- tests/interfaces.py
> User detail

- .dockerignore
- .gitignore
- .stylelintrc.json
- Makefile
- docs/_static/custom.css
- magpie/ui/home/static/style.css
- magpie/ui/home/static/themes/green.css
- add makefile targets check/fix-css[-only to validate CSS styles formatting
> css linting check

- docs/authentication.rst
- docs/installation.rst
improve magpie install instructions to avoid confusion with other packages
> docs install updates

- CHANGES.rst
- config/magpie.ini
- magpie/ui/home/static/style.css
Fixes erroneous config variable name.
> fix erroneous config variable name

- requirements-dev.txt
- requirements-doc.txt
- requirements-sys.txt
- requirements.txt
Resolve SNYK-PYTHON-SETUPTOOLS-3113904
Closes #533 
Closes #543
> pin setuptools  and depends requirements-sys by all other requirements

- .github/workflows/tests.yml
- .pylintrc
- CHANGES.rst
- magpie/cli/sync_resources.py
- magpie/cli/sync_services.py
- magpie/typedefs.py
- magpie/ui/home/static/style.css
- magpie/ui/management/templates/edit_service.mako
- magpie/ui/management/views.py
- requirements-dev.txt
- setup.cfg
- add sync-type to UI 
- improve sync-related typings 
- fix missing resource-type after sync (fixes https://github.com/Ouranosinc/Magpie/issues/549)
> fixes related to resource sync

- README.rst
Relates to https://github.com/badges/shields/issues/8671
> fix GitHub CI badge URL 

- CHANGES.rst
- Makefile
- magpie/alembic/versions/2012-06-27_3cfc41c4a5f0_groups_pkey_change.py
- magpie/alembic/versions/2012-07-07_20671b28c538_change_all_linking_k.py
- magpie/alembic/versions/2016-04-02_57bbf0c387c_add_local_user_id.py
- magpie/utils.py
- requirements.txt
- add tween to force close transaction after request/response handling 
- unpin `alembic` for latest updates
> add tween to force close transaction after request/response handling 

- .pylintrc
- Makefile
- docs/_ext/doc_redirect.py
- docs/authentication.rst
- docs/glossary.rst
- docs/permissions.rst
- docs/references.rst
- docs/usage.rst
- magpie/alembic/versions/2018-05-23_2a6c63397399_separate_personal_standard_groups.py
- magpie/alembic/versions/2022-09-01_5e5acc33adce_case_insensitive_email_constraint.py
- magpie/api/login/login.py
- magpie/api/management/service/service_views.py
- magpie/api/management/user/user_utils.py
- magpie/api/webhooks.py
- magpie/models.py
- magpie/security.py
- magpie/ui/login/views.py
- tests/interfaces.py
- tests/test_adapter.py
- tests/test_magpie_api.py
- tests/test_register.py
- tests/utils.py
Fix the permissions example in [Ouranosinc/Magpie@fix-docs-example/docs/permissions.rst](https://github.com/Ouranosinc/Magpie/compare/fix-docs-example?expand=1#diff-9cdf52695210be488a07bb9d41acd2adec865440097187b6ffdf3a1cdff78465)
> fix doc permissions example and other docs linting

- .github/workflows/label.yml
- CHANGES.rst
- Dockerfile
- requirements-sys.txt
* Security fix: bump Docker base ``python:3.11-alpine3.19``.
> apply recommended security fixes
